Car/urls.py
from django.urls import path, include
from car import views

urlpatterns = [
    # Home Page -------------------------------------
    path('home/', views.index, name='index'),

    # LatestModels Details Page ----------------------
    path('detail_latmodel/<int:LatestModel_id>/', views.detail_latmodel, name='detail_latmodel'),

    # Category Page (All Models of Cars) ----------------------
    path('category/<slug:val>', views.CategoryView.as_view(), name='category'),

    # Details Page of Category ----------------------------
    path('detail_category/<int:pk>/', views.detail_category.as_view(), name='detail_category'),

    # Buy Online Page ----------------------------------
    path('online/', views.online, name='online'),

    # Details Page of Online ----------------------------
    path('detail_online/<int:MBOnline_id>/', views.detail_online, name='detail_online'),

    # Service Page --------------------------------------
    path('service/', views.Services, name='Services'),

    # Brand Page ----------------------------------
    path('brand/', views.Brands, name='Brands'),

    # To Add New Models ------------------------------
    path('addmodels/', views.create_MBModel, name='create_MBModel'),

    # To Add New Buy Online Models ---------------------
    path('addonline/', views.create_MBOnline, name='create_MBOnline'),

    # To Edit Models ------------------------------------
    path('updatemodel/<int:id>/', views.update_MBModel, name='update_MBModel'),

    # To Delete Models ----------------------------------
    path('deletemodel/<int:id>/', views.delete_MBModel, name='delete_MBModel'),

    # To Update Buy Online Models ----------------------------
    path('updateonline/<int:id>/', views.update_MBOnline, name='update_MBOnline'),

    # To Delete Buy Online Models ---------------------------
    path('deleteonline/<int:id>/', views.delete_MBOnline, name='delete_MBOnline'),

    # To Add Latest Models ------------------------------------
    path('addlatmodels/', views.create_latmodel, name='create_latmodel'),

    # To Edit Latest Models -------------------------------
    path('updatelatmodels/<int:id>/', views.update_latmodel, name='update_latmodel'),

    # To Delete Latest Models --------------------------
    path('deletelatmodel/<int:id>/', views.delete_latmodel, name='delete_latmodel'),

    # To Add Services ----------------------------
    path('addservice/', views.create_service, name='create_service'),

    # To Add Brand ------------------------------------------
    path('addbrand/', views.create_brand, name='create_brand'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import views as userviews

urlpatterns = [
    # Admin Page ------------------------------
    path('admin/', admin.site.urls),

    # Car includes -------------------------------
    path('car/', include ('car.urls')),

    # Users Includes ----------------------------
    path('users/', include('users.urls')),

    # Register/Sign Up Page -----------------------
    path('register/', userviews.register, name='register'),

    # Login Page ------------------------------------
    path('login/', userviews.login_view, name='login'),

    # Logout Page --------------------------------------
    path('logout/', userviews.logout_view, name='logout'),

    # Profile Page ------------------------------------
    path('profile/', userviews.ProfilePage, name='profile'),

    # Profile Form Page -----------------------------------------
    path('profform/<int:prof_id>/', userviews.ProfileForm, name='profform'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    # Test Drive Form Page --------------------------------
    path('testdrive-form/', views.test_drive, name='test_drive'),

    # Finance Page ----------------------------------
    path('Finance/', views.finance, name='finance'),

    # Fianace-Form Page -----------------------------
    path('Finance-Form/', views.finance_form, name='finance_form'),

    # EMI page -------------------------------------
    path('EMI/', views.emimodel, name='emimodel'),

    # Shop Online Page --------------------------------
    path('ShopOnline/', views.shoponline, name='shoponline'),

    # Details of Shop Online Page -----------------------
    path('detail_shop/<int:ShopOnline_id>/', views.detail_shop, name='detail_shop'),

    # Shop-TestDrive Form --------------------------------
    path('shop_testdrive-form/', views.Shop_TestDrive, name='Shop_TestDrive'),

    # Buy Now Form ------------------------------
    path('buynow-form/', views.buy_now, name='buy_now'),

    # Location Form ----------------------------
    path('location-form/', views.location, name='location'),

    # Feedback Form --------------------------------
    path('Feedback-form/', views.feedback, name='feedback'),
]

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from users.forms import RegisterForm, ProfForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from users.models import Profile
from .forms import TestDriveForm
from .models import Car, Cust_TestDrive
from .forms import FinancingForm
from .models import Financing
from .forms import EmiModelForm
from django.views import View
from .models import EmiModels
from .models import ShopOnline
from .forms import shoptestdriveform
from .models import shop_testdrive
from .forms import BuyNowform
from .models import BuyNow
from .forms import Locationform
from .models import Location
from .forms import FeedbackForm
from .models import Feedback
from .models import Feedback_satisfied


# Create your views here.

# Register/Sign Up Page --------------------------------
def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request,
                'Welcome {}, your account has been scuccessfully created. Now you may login below'.format(username)
            )
            return redirect('login')
    else:
        form = RegisterForm()
    
    context = {
        'form':form
    }

    return render(request, 'users/register.html', context)


# Login Page ------------------------------------
def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is None:
            messages.success(
                request,
                'Invalid Login, try again'.format(user)
            )
            return redirect('login')

        elif user.is_superuser:
            login(request, user)
            messages.success(
                request, 
                'Welcome {} A SuperUser, you have been logged in successfully'.format(user)
            )
            return redirect('index')

        elif user is not None:
            login(request, user)
            messages.success(
                request,
                'Welcome {}, you have been logged in successfully'.format(user)
        )
        return redirect('index')
        
    return render(request, 'users/login.html')


# LogOut Page ----------------------------------------
def logout_view(request):

    if request.method == 'POST':
        user = request.user.username
        logout(request)
        messages.success(
            request,
            '{}, you have been logged out successfully'.format(user)
        )
        return redirect('index')
    
    return render(request, 'users/logout.html')


# Profile Page ---------------------------------------
def ProfilePage(request):
    prof = Profile.objects.get(id = request.user.id)

    if not request.user.is_authenticated:
        return redirect('login')
    
    context = {
        'prof':prof
    }

    return render(request, 'users/profile.html', context)


# Profile Form Page -------------------------------------
def ProfileForm(request, prof_id):
    prof = Profile.objects.get(id=prof_id)

    form = ProfForm(request.POST or None, request.FILES or None, instance=prof)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form':form
    }

    return render(request, 'users/profform.html', context)


# Test Drive Form --------------------------------------
def test_drive(request):

    if request.method == 'POST':
        form = TestDriveForm(request.POST)
        if form.is_valid():
            car_model = form.cleaned_data['car_model']
            Salutation = form.cleaned_data['salutation']
            FirstName = form.cleaned_data['FirstName']
            LastName = form.cleaned_data['LastName']
            EmailID = form.cleaned_data['EmailID']
            MobileNo = form.cleaned_data['MobileNo']
            PreferredCity = form.cleaned_data['PreferredCity']
            
            CustTestDrive = Cust_TestDrive.objects.create(
                car_model = car_model,
                Salutation = Salutation,
                FirstName = FirstName,
                LastName = LastName,
                EmailID = EmailID,
                MobileNo = MobileNo,
                PreferredCity = PreferredCity
            )
            messages.success(
                request,
                'Thank You!.. Your Test Drive has Booked Successfully. We will contact you Shortly..'
            )

            return redirect('index')
        
    else:
        form = TestDriveForm()

    context = {
        'form':form
    }

    return render(request, 'users/testdrive-form.html', context)


# Finance Form ---------------------------------------
def finance(request):
    return render(request, 'users/Finance.html')

def finance_form(request):

    if request.method == 'POST':
        form = FinancingForm(request.POST)
        if form.is_valid():

            Salutation = form.cleaned_data['Salutation']
            FirstName = form.cleaned_data['FirstName']
            LastName = form.cleaned_data['LastName']
            EmailID = form.cleaned_data['EmailID']
            MobileNo = form.cleaned_data['MobileNo']
            
            Finance = Financing.objects.create(
                Salutation = Salutation,
                FirstName = FirstName,
                LastName = LastName,
                EmailID = EmailID,
                MobileNo = MobileNo,
            )
            messages.success(
                request,
                'Thank You!.. We will contact you Shortly..'
            )

            return redirect('index')
        
    else:
        form = FinancingForm()

    context = {
        'form':form
    }

    return render(request, 'users/Finance-Form.html', context)


# EMI Models -------------------------------------
def emimodel(request):
    if request.method == 'POST':
        form = EmiModelForm(request.POST)
        if form.is_valid():
            model_names_id = form.cleaned_data['model_names']
            modelname_data = EmiModels.objects.get(id = model_names_id)
            
            return render(request, 'users/EMI.html', { 'modelname_data':modelname_data })
    
    else:
        form = EmiModelForm()
    

    context = {
        'form':form
    }

    return render(request, 'users/EMI.html', context)


# Shop Online ---------------------------------------
def shoponline(request):

    shop_online = ShopOnline.objects.all()

    context = {
        'shop_online':shop_online
    }

    return render(request, 'users/ShopOnline.html', context)


# Details of Shop Online ----------------------------
def detail_shop(request, ShopOnline_id):

    detailshop = ShopOnline.objects.get(id = ShopOnline_id)

    context = {
        'detailshop':detailshop
    }

    return render(request, 'users/detail_shop.html', context)


# Shop - TestDrive Form Page --------------------------------
def Shop_TestDrive(request):

    if request.method == 'POST':
        form = shoptestdriveform(request.POST)
        if form.is_valid():
            carmodel = form.cleaned_data['carmodel']
            salutation = form.cleaned_data['salutation']
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            email = form.cleaned_data['email']
            MobileNo = form.cleaned_data['MobileNo']
            
            shoptestdrive = shop_testdrive.objects.create(
                carmodel = carmodel,
                salutation = salutation,
                firstname = firstname,
                lastname = lastname,
                email = email,
                MobileNo = MobileNo,
            )
            messages.success(
                request,
                'Thank You!.. Your Test Drive has Booked Successfully. We will contact you Shortly..'
            )

            return redirect('index')
        
    else:
        form = shoptestdriveform()

    context = {
        'form':form
    }

    return render(request, 'users/shop_testdrive-form.html', context)


# Buy Now Form Page ---------------------------------------
def buy_now(request):

    if request.method == 'POST':
        form = BuyNowform(request.POST)
        if form.is_valid():
            carmodel = form.cleaned_data['carmodel']
            salutation = form.cleaned_data['salutation']
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            email = form.cleaned_data['email']
            MobileNo = form.cleaned_data['MobileNo']
            
            BUYNOW = BuyNow.objects.create(
                carmodel = carmodel,
                salutation = salutation,
                firstname = firstname,
                lastname = lastname,
                email = email,
                MobileNo = MobileNo,
            )
            messages.success(
                request,
                'Congratulations!.. Your Mercedes Benz has Booked Successfully. We will contact you soon. Thank You!..'
            )

            return redirect('index')
        
    else:
        form = BuyNowform()

    context = {
        'form':form
    }


users/templates/users/EMI-calculate.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

<h1>Emi Calculator</h1>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card"><br><br>
                <div class="card-header text-white bg-dark text-center">
                    <div class="card-title">
                        Personal Details
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
        
                        <br><br><label>Model Name: </label><br>
                        {{ form.model_name }}
                            
                        <br><br><label>Rate of Interest: </label><br>
                        {{ form.interest_rate }}
                            
                        <br><br><label>No. of Years: </label><br>
                        {{ form.term_in_years }}

                        <a href="{% static 'users/EMI.html' %}">
                            <br><br><button type="submit" class="btn btn-dark btn btn-sm">Submit</button>
                        </a> 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div><br>

<!-- <h1>Emi Calculator</h1>

<h1>EMI Calculation Result</h1>
<p>EMI: {{ emi }}</p> -->

{% endblock %}

users/templates/users/EMI.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

<br><div class="row bg-dark text-centre p-2 text-white border bottom shadow">
    <h2 style="margin-left: 40%;"><b>EMI CALCULATOR</b></h2>
</div><br>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card"><br><br>
                <div class="card-header text-white bg-dark text-center">
                    <div class="card-title">
                        Car
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
        
                        <br><br><label><b>Choose Your Car: </b></label><br>
                        {{ form }}
                            
                        <br><button type="submit" class="btn btn-dark btn btn-sm">Submit</button> 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div><br><br>

{% if modelname_data %}


    <div class="row">
        <div class="col-md-6 offset-md-1">
            <img src="{{ modelname_data.image.url }}" alt="{{ modelname_data.model_name }}" class="card" height="500px" width="650px">
        </div>
            <div class="card-header">
                <h2><b>Your Selected Model:</b></h2><br>
                <h3><b>{{ modelname_data.bodytype }}</b></h3>
                <h3><b>{{ modelname_data.model_name }}</b></h3><br>
                <h4><b>Price: </b>${{ modelname_data.car_price }}</h4><br>
                <h4><b>Down Payment: </b>${{ modelname_data.down_payment }}</h4><br>
                <h4><b>Finanace Amount: </b>${{ modelname_data.fin_amount }}</h4><br>
                <h4><b>Interest Rate: </b>{{ modelname_data.interest_rate }}% (Yearly)</h4><br>
                <h4><b>Tenure Period (Years): </b>{{ modelname_data.tenure_years }} years</h4><br>
                <h4><b>EMI: </b>${{ modelname_data.emi }}</h4><br>
            </div>
    </div>
<br><br>
{% endif %}

{% endblock %}


users/templates/users/Feedback-form.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

    <br><br><div class="row bg-dark text-centre p-3 text-white border bottom shadow">
        <h1 style="margin-left: 30%"><b>Enter Your Feedback<b></h1><br><br>
    </div><br>

    <div class="offset-md-4">
        <h4>We value your Feedback. Please fill the below Form.</h4>
    </div><br>

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card"><br><br><br>
                    <div class="card-header text-white bg-dark text-center">
                        <div class="card-title">
                            Feedback Form
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}

                            <br><br><label>Enter Your Full Name: </label><br>
                            {{ form.name }}
            
                            <br><br><label>How much are you satisfied with our Mercedes-Benz? </label><br>
                            {{ form.Satisfied }}
                            
                            <br><br><label>Will you give any Recommendations our Mercedes-Benz to others? (Optional) </label><br>
                            {{ form.recommend }}

                            <br><br><button type="submit" class="btn btn-dark btn btn-sm">Save</button>
                                <a href="{% url 'index' %}" class="btn btn-danger btn btn-sm">
                                    No, Thank You!..
                                </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>

    <div class="row bg-dark text-centre p-3 text-white border bottom shadow"></div><br>

{% endblock %}

users/templates/users/ShopOnline.html
{% extends 'car/base.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}

    <br><div class="row bg-dark text-centre p-2 text-white border bottom shadow">
        <h2 style="margin-left: 38%;"><b>Shop Your Mercedes-Benz</b></h2>
    </div><br>

    <div class="col-sm-10">
        <div class="row">
            {% for ShopOnline in shop_online %}
                <div class="col text-align">
                    <div class="offset-md-2">
                        <div style="display: block; margin:auto">
                            <img src="{{ ShopOnline.image.url }} " class="card-header" height="450px" width="600px">
                        </div>
                    </div><br>

                    <div class="offset-md-1">
                        <h1 style="font-size: 2rem; margin-left:24lvh"><b>{{ ShopOnline.car_body }}</b></h1>
                        <h3 style="font-style: initial; margin-left:24lvh"><b>{{ ShopOnline.modelname }}</b></h2>
                        <h4 style="font-style: initial; margin-left:24lvh">On-Road Price: ${{ ShopOnline.price }}</h4>
                        <h4 style="font-style: initial; margin-left:24lvh">Monthly Installment: ${{ ShopOnline.monthly_emi }}</h4>
                    </div><br>

                    <div class="offset-md-1" style="margin-left: 35lvh">
                        <a href="{% url 'users:detail_shop' ShopOnline.id %}" style="width: 200px; text-align: center" class="btn btn-danger">
                            <h3><b>Explore</b></h3>
                        </a>
                    </div><br><br><br>
                </div>
                
            {% endfor %}
        </div>
    </div>

    <div class="row bg-dark text-centre p-3 text-white border bottom shadow"></div><br>

    {% endblock %}
</body>
</html>

users/templates/users/buynow-form.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

    <br><br><div class="row bg-dark text-centre p-3 text-white border bottom shadow">
        <h1 style="margin-left: 30%"><b>BOOK YOUR MERCEDES-BENZ NOW<b></h1><br><br>
    </div><br>

    <div class="offset-md-4">
        <h4>Please fill the details below to book your Mercedes-Benz.</h4>
    </div><br>

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card"><br><br><br>
                    <div class="card-header text-white bg-dark text-center">
                        <div class="card-title">
                            BOOK NOW
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}

                            <br><br><label>Your Mercedes-Benz Model: </label><br>
                            {{ form.carmodel }}
            
                            <br><br><label>Salutation [Mr, Mrs, Ms.]: </label><br>
                            {{ form.salutation }}
                                
                            <br><br><label>First Name: </label><br>
                            {{ form.firstname }}
                                
                            <br><br><label>Last Name: </label><br>
                            {{ form.lastname }}
                                
                            <br><br><label>Email Id: </label><br>
                            {{ form.email }}
                                
                            <br><br><label>Mobile Number: </label><br>
                            {{ form.MobileNo }}
                                
                            <br><br><button type="submit" class="btn btn-dark btn btn-sm">BOOK NOW</button> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>

    <div class="row bg-dark text-centre p-3 text-white border bottom shadow"></div><br>


{% endblock %}

users/templates/users/detail_shop.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

    <br><br><div class="row">
        <div class="col-md-6 offset-md-1 card-header">
            <img src="{{ detailshop.image.url }}" class="card" height="550px" width="730px"><br>
            <h2 style="font-style: initial; font-size: 1.5rem"><b>{{ detailshop.modelname }}</b></h2><br>
            <h4 style="font-style: italic; font-size: 1rem; text-align: justify">{{ detailshop.description }}</h4><br>
        </div>

        <div class="offset-md-1 card-header">
            <br><br><h1 style="font-size: 2rem"><b>{{ detailshop.car_body }}</b></h1><br>
            <h2 style="font-style: initial; font-size: 1.5rem"><b>{{ detailshop.modelname }}</b></h2><br>
            <h4 style="font-style: initial; font-size: 1.5rem; text-align: justify"><b>{{ detailshop.fuel_type }}</b></h4><br>
            <h4 style="font-style: initial; font-size: 1.5rem; text-align: justify"><b>{{ detailshop.kW }}</b></h4><br>
            <h4><b>On-Road Price: </b>${{ detailshop.price }}</h4>
            <h4><b>Monthly Installment: </b>${{ detailshop.monthly_emi }}</h4><br><br>
            <h2><b><u>Explore Finance Option</u></b></h2><br>
            <h4><b>Down Payment: </b>${{ detailshop.down_payment }}</h4>
            <h4><b>Finance Amount: </b>${{ detailshop.fin_amount }}</h4>
            <h4><b>Tenure Period: </b>{{ detailshop.tenure_months }} Months</h4><br>
            
            <a href="{% url 'users:Shop_TestDrive' %}" style="width: 300px; text-align: center" class="btn btn-warning">
                <h4><b>Book A Test Drive</b></h4>
            </a><br><br>

            <a href="{% url 'users:buy_now' %}" style="width: 300px; text-align: center" class="btn btn-primary">
                <h4><b>BOOK NOW</b></h4>
            </a>
        </div>
    </div><br><br>


{% endblock %}

users/templates/users/location-form.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

    <br><br><div class="row bg-dark text-centre p-3 text-white border bottom shadow">
        <h1 style="margin-left: 30%"><b>Register Your Location Details<b></h1><br><br>
    </div><br>

    <div class="offset-md-2">
        <h4>Please enter your Location details so we can provide you our Best Services effectively.</h4>
    </div><br>

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card"><br><br><br>
                    <div class="card-header text-white bg-dark text-center">
                        <div class="card-title">
                            ENTER LOCATION DETAILS
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}

                            <br><br><label>Your Full Name: </label><br>
                            {{ form.name }}

                            <br><br><label>State: </label><br>
                            {{ form.state }}
            
                            <br><br><label>City: </label><br>
                            {{ form.city }}
                                
                            <br><br><label>Pincode[Please 6-Digits pincode eg:401202]: </label><br>
                            {{ form.pincode }}
                                
                            <br><br><button type="submit" class="btn btn-dark btn btn-sm">Save</button> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>

    <div class="row bg-dark text-centre p-3 text-white border bottom shadow"></div><br>
{% endblock %}

users/templates/users/login.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

<!-- <div class="container"> -->
    <div class="row">
        <!-- <img src="{% static 'car/images/login1.jpg' %}" width="70%" height="80%"> -->
        <div class="col-md-6 offset-md-3">
            <div class="card"><br><br>
                <div class="card-header text-dark bg-info">
                    <div class="card-title">
                        <h3>Mercedes Me Login..</h3>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{% static 'car/images/login1.jpg' %}" width="100%" height="80%">
                    <form method="POST">
                        {% csrf_token %}

                        <br><label for="user">Username: </label><br>
                        <input type="text" id="user" name="username"><br>

                        <label for="pass">Password: </label><br>
                        <input type="password" id="user" name="password"><br><br>

                        <button type="submit" class="btn btn-success" style="width: 60%;"><b>Login</b></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

users/templates/users/logout.html
{% extends 'car/base.html' %}

{% load static %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card"><br><br><br><br>
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        LogOut
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <h6> Are you sure you want to Logout? </h6>
                        <button type="submit" class="btn btn-success btn btn-sm">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}